name: Data Extraction

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r ./docs/requirements.txt
      - name: Run Data Extraction
        run: |
          python ./scripts/data_processing.py --extract
