name: Lint Code
on:
    push:
        paths:
          - "**/**"
    pull_request:
        paths:
          - "**/**"
    schedule:
        - cron: 0 0 * * 0
jobs:
    lint:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version:
            ['3.8','3.9','3.10','3.11','3.12']
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install linting dependencies
          run: |
            pip install flake8 black  # Install linters
        - name: Run flake8 Linting
          run: |
            flake8 scripts  # Lint the Scripts directory with flake8
          continue-on-error: false
        - name: Run black Linting
          run: |
            black --check scripts  # Check formatting with black
          continue-on-error: false
    
